name: build article pdf
on:
  push:
  workflow_call:
  pull_request:
    branches:
      - main

env:
  INPUT_PATH: article/article.pandoc.md
  RESOURCE_PATH: article
  BIB_PATH: slides/bibliography.bib
  OUTPUT_PATH: article/24_bis_shibboleth_article.pdf
  ARTIFACT_NAME: 24_bis_shibboleth_article

# make sure that GITHUB_TOKEN has permissions
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Build pdf
        uses: docker://pandoc/latex:latest
        with:
          args: >-
            --shift-heading-level-by=-1
            --resource-path ${{ env.RESOURCE_PATH }} \
            --bibliography ${{ env.BIB_PATH }} \
            --citeproc
            ${{ env.INPUT_PATH }}
            -o ${{ env.OUTPUT_PATH }}
      
      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.OUTPUT_PATH }}
