name: release
on:
  push:
    tags:
      - '*'

env:
  SLIDES_ARTIFACT_NAME: 24_bis_shibboleth_slides
  ARTICLE_ARTIFACT_NAME: 24_bis_shibboleth_article

jobs:
  build-slides:
    uses: ./.github/workflows/build_slides.yaml
  
  build-article:
    uses: ./.github/workflows/build_article_pdf.yaml

  release:
      runs-on: ubuntu-latest
      needs: [ build-slides, build-article ]
      # make sure that GITHUB_TOKEN has permissions
      permissions:
        contents: write
      steps:
        - name: Download slides artifact
          uses: actions/download-artifact@v4
          with:
            pattern: ${{ env.SLIDES_ARTIFACT_NAME }}

        - name: Download article artifact
          uses: actions/download-artifact@v4
          with:
            pattern: ${{ env.ARTICLE_ARTIFACT_NAME }}
          
        - name: Create release
          uses: ncipollo/release-action@v1.14.0
          with:
            artifacts: ${{ env.SLIDES_ARTIFACT_NAME }}/*, ${{ env.ARTICLE_ARTIFACT_NAME }}/*
            body: "Release of version ${{ github.ref_name }}"
            allowUpdates: true
