name: release
on:
  push:
    tags:
      - '*'

env:
  # without extension
  # see env.OUTPUT_NAME in `build.yaml`
  ARTIFACT_NAME: 24_bis_shibboleth_slides

jobs:
  build:
    uses: ./.github/workflows/build_slides.yaml

  release:
      runs-on: ubuntu-latest
      needs: build
      # make sure that GITHUB_TOKEN has permissions
      permissions:
        contents: write
      steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: ${{ env.ARTIFACT_NAME }}
          
        - name: Create release
          uses: ncipollo/release-action@v1.14.0
          with:
            artifacts: ${{ env.ARTIFACT_NAME }}.pdf
            body: "Release of version ${{ github.ref_name }}"
            allowUpdates: true
