name: update article preview
on:
  push:
    paths:
      - article/article.pandoc.md

env:
  INPUT_PATH: article/article.pandoc.md
  PREVIEW_PATH: article/artic.preview.md

# make sure that GITHUB_TOKEN has permissions
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      - name: Build preview
        uses: docker://pandoc/core:latest
        with:
          args: >-
            --shift-heading-level-by=-1
            --citeproc
            --to=gfm
            -o ${{ env.PREVIEW_PATH }}
            ${{ env.INPUT_PATH }}

      - name: Commit preview
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add ${{ env.PREVIEW_PATH }}
            git commit -m "[CI] Update previews." || echo "No changes to commit."
